### ISSUE TITLE
feat: femboy animal breeding

### ISSUE THREAD

**Issue by ghost** [toastxc/Reywen-TXC#1]
add a `?t breed <animal>` command for breeding animals, which requires two or more of that animal and adds a random number (1-5) of it to your collection

**Comment by toastxc** [comment]
ok so how should this work?
- can two animals of different species be able to breed, if so what is the outcome?
- should this feature be 'unlocked' or enabled by default for all users

**Comment by ghost** [comment]
crossbreeding should cost you a shit ton of money and have a 20% chance of working to give you some abomination

**Comment by toastxc** [comment]
\>->
the database driver is strictly typed, how should an abomination be stored?

**Comment by ghost** [comment]
Abomination type, with additional metadata

**Comment by toastxc** [comment]
\>->
right

**Comment by toastxc** [comment]
well i've been planning a rewrite for this plugin for a long time so i might as well reconsider how data is stored
